### ISSUE TITLE
breaks the transmitter

### ISSUE THREAD

**Issue by therealmrnerd** [Xaymar/lb2-uberduckai#1]
On installing to Sammi Bridge ie the Transmitter it install as <tr and breaks the transmitter

**Comment by Xaymar** [comment]
Try using Firefox.

**Comment by therealmrnerd** [comment]
Might be an issue when I stream via OBS and use Chrome. Not to worry but at least you're aware of the issue.Out and About on my Mobile so no fancy signature
-------- Original message --------From: Xaymar ***@***.***> Date: 05/10/2022  16:14  (GMT+00:00) To: Xaymar/lb2-uberduckai ***@***.***> Cc: therealmrnerd ***@***.***>, Author ***@***.***> Subject: Re: [Xaymar/lb2-uberduckai] breaks the transmitter (Issue #1) 
Try using Firefox.

**Comment by Xaymar** [comment]
Chrome has an incredibly low websocket limit, which is not documented anywhere.

**Comment by therealmrnerd** [comment]
I wouldn't really know, I just keep the transmitter/bridge in an OBS browser dock and let it do it's thing. Web sockets aren't really something I know a great deal about thus I use Sammi/Lioranboard.Out and About on my Mobile so no fancy signature
-------- Original message --------From: Xaymar ***@***.***> Date: 06/10/2022  06:04  (GMT+00:00) To: Xaymar/lb2-uberduckai ***@***.***> Cc: therealmrnerd ***@***.***>, Author ***@***.***> Subject: Re: [Xaymar/lb2-uberduckai] breaks the transmitter (Issue #1) 
Chrome has an incredibly low websocket limit, which is not documented anywhere.
